### ISSUE TITLE
creating cube at runtime doesn't work

### ISSUE THREAD

**Issue by timepp** [larspetrus/Roofpig#14]
is there a way to fix the cubes I created using JavaScript at run-time? 
my code runs after a button is clicked:
```javascript
function on_button_click() {
    for (var i in F2L) {
        var c = F2L[i];
        var $div = $("<div>")
            .append($("<p>").addClass("description").text(c.situation))
            .append($("<p>").text(c.note));
        for (var j in c.maneuvers) {
            var maneuver = c.maneuvers[j];
            $div.append($("<div>").addClass("roofpig").attr("data-config", maneuver));
        }
        $div.appendTo("body");
    }
}
```

**Comment by larspetrus** [comment]
Sorry, looks like I forgot to actually document how to do this... :(

You call `CubeAnimation.create_in_dom(parent_selector, config, div_attributes)`, where...
- `parent_selector` is the dom element to create the cube in
- `config` is the Roofpig config string, and
- `div_attributes` are mostly for adding classes.

You can see it working here: http://birdflu.lar5.com/?pos=Cr4i

**Comment by timepp** [comment]
awesome man! thanks~
