### ISSUE TITLE
CubeAnimation.create_in_dom does not work

### ISSUE THREAD

**Issue by albaserver** [larspetrus/Roofpig#25]
Hello,
I'm trying to use Roofpig, I need to load dynamically a cube but the animation does not start.

Here's the code  (it's simple but I need to load the content dynamically and not statically). The cube is loaded but the animation does not start in any case (click on play,, plus, press bar space, ...).

```
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<script src="jquery.min.3.1.1.js"></script>
<script src="roofpig_and_three.min.js"></script>
</head>
<body>
<div id="animation" style="width:30%; margin:auto;"></div>

<div id="loadAnimation">click here to load animation</div>

<script>
document.getElementById("loadAnimation").onclick=function()
{
	CubeAnimation.create_in_dom('#animation', "alg=L' R U R' U' L R' F R F'|colored=u|hover=2|speed=1000|flags=showalg|colors=U:y F:b R:r B:g L:o D:w", "class='my-roofpig'");
	this.parentNode.removeChild(this);
};
</script>
</body>
</html>
```

**Comment by albaserver** [comment]
I'm sorry, yesterday I was so tired. the class is roofpig and not my-roofpig, so the code is:

`CubeAnimation.create_in_dom('#animation', "alg=L' R U R' U' L R' F R F'|colored=u|hover=2|speed=1000|flags=showalg|colors=U:y F:b R:r B:g L:o D:w", "class='roofpig'");`

**Comment by larspetrus** [comment]
Glad things worked out :)
